# Generated by Django 5.2.7 on 2025-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age_group',
            field=models.CharField(blank=True, choices=[('KID', 'Niño (6-9 años)'), ('TWEEN', 'Preadolescente (10-12 años)'), ('TEEN', 'Adolescente (13-16 años)')], max_length=10, null=True),
        ),
    ]
