# Generated by Django 5.2.7 on 2025-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed_once',
            field=models.BooleanField(default=False),
        ),
    ]
