# Generated by Django 5.2.7 on 2025-11-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_email_verified',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_expires_at',
            new_name='verification_code_expires_at',
        ),
    ]
