# Generated by Django 5.2.7 on 2025-11-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_is_email_verified_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
